name: iOS CI - Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    name: Run Unit Tests
    runs-on: self-hosted

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Show Xcode version
      - name: Show Xcode Version
        run: xcodebuild -version

      # 3. List schemes
      - name: List Schemes
        run: xcodebuild -list

      # 4. Run Unit Tests
      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -scheme MovieMosaic \
          -sdk iphonesimulator \
          -parallel-testing-enabled NO \
          -destination 'platform=iOS Simulator,name=iPhone 17' \
          -resultBundlePath UnitTests.xcresult \
          -only-testing:MovieMosaicTests


  ui_tests:
    name: Run UI Tests
    runs-on: self-hosted
    needs: unit_tests

    steps:
      # 1. Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Show Xcode version
      - name: Show Xcode Version
        run: xcodebuild -version

      # 3. List schemes
      - name: List Schemes
        run: xcodebuild -list

      # 4. Run UI Tests
      - name: Run UI Tests
        run: |
          xcodebuild test \
          -scheme MovieMosaic \
          -sdk iphonesimulator \
          -parallel-testing-enabled NO \
          -destination 'platform=iOS Simulator,name=iPhone 17' \
          -resultBundlePath UITests.xcresult \
          -only-testing:MovieMosaicUITests
